In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits = load_digits()

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.3)

In [23]:
def get_score(model, X_train, X_test, y_train, y_test): 
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [24]:
from sklearn.model_selection import StratifiedKFold

In [27]:
kf = StratifiedKFold(n_splits = 3)

In [31]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_lr.append(get_score(LogisticRegression(max_iter = 1000), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators = 40), X_train, X_test, y_train, y_test))


In [32]:
scores_lr

[0.9198664440734557, 0.9432387312186978, 0.9165275459098498]

In [33]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [34]:
scores_rf

[0.9282136894824707, 0.9549248747913188, 0.9282136894824707]

In [35]:
from sklearn.model_selection import cross_val_score

In [37]:
cross_val_score(LogisticRegression(max_iter = 1000), digits.data, digits.target)

array([0.92222222, 0.86944444, 0.94150418, 0.94150418, 0.89693593])

In [38]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [39]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.925     , 0.90277778, 0.95543175, 0.96935933, 0.93593315])